include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
  errors:
    inference_failure_on_collection_literal: ignore
    inference_failure_on_function_invocation: ignore
    lines_longer_than_80_chars: ignore

linter:
  rules:
  - avoid_bool_literals_in_conditional_expressions
  - prefer_final_in_for_each
  - prefer_final_locals
