// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Provides metadata about GeneratedMessage and ProtobufEnum to
/// dart-protoc-plugin. (Experimental API; subject to change.)
/// @nodoc
library protobuf.meta;

// ignore_for_file: constant_identifier_names

// List of names which cannot be used in a subclass of GeneratedMessage.
const GeneratedMessage_reservedNames = <String>[
  '==',
  'GeneratedMessage',
  'Object',
  'addExtension',
  'check',
  'clear',
  'clearExtension',
  'clearField',
  'clone',
  'copyWith',
  'createEmptyInstance',
  'extensionsAreInitialized',
  'freeze',
  'getDefaultForField',
  'getExtension',
  'getField',
  'getFieldOrNull',
  'getTagNumber',
  'hasExtension',
  'hasField',
  'hasRequiredFields',
  'hashCode',
  'info_',
  'isFrozen',
  'isInitialized',
  'mergeFromBuffer',
  'mergeFromCodedBufferReader',
  'mergeFromJson',
  'mergeFromJsonMap',
  'mergeFromMessage',
  'mergeFromProto3Json',
  'mergeUnknownFields',
  'noSuchMethod',
  'runtimeType',
  'setExtension',
  'setField',
  'setFieldNullable',
  'toBuilder',
  'toDebugString',
  'toProto3Json',
  'toString',
  'unknownFields',
  'writeToBuffer',
  'writeToCodedBufferWriter',
  'writeToJson',
  'writeToJsonMap',
  r'$_clearField',
  r'$_ensure',
  r'$_get',
  r'$_getNullable',
  r'$_getI64',
  r'$_getI64Nullable',
  r'$_getList',
  r'$_getMap',
  r'$_getN',
  r'$_getB',
  r'$_getBF',
  r'$_getBNullable',
  r'$_getI',
  r'$_getIZ',
  r'$_getINullable',
  r'$_getS',
  r'$_getSZ',
  r'$_getSNullable',
  r'$_has',
  r'$_setBool',
  r'$_setBoolNullable',
  r'$_setBytes',
  r'$_setBytesNullable',
  r'$_setDouble',
  r'$_setDoubleNullable',
  r'$_setField',
  r'$_setFieldNullable',
  r'$_setFloat',
  r'$_setFloatNullable',
  r'$_setInt64',
  r'$_setInt64Nullable',
  r'$_setSignedInt32',
  r'$_setSignedInt32Nullable',
  r'$_setString',
  r'$_setStringNullable',
  r'$_setUnsignedInt32',
  r'$_setUnsignedInt32Nullable',
  r'$_whichOneof',
];

// List of names which cannot be used in a subclass of ProtobufEnum.
const ProtobufEnum_reservedNames = <String>[
  '==',
  'Object',
  'ProtobufEnum',
  'hashCode',
  'noSuchMethod',
  'runtimeType',
  'toString'
];
