include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_dynamic_calls
    - comment_references
    - directives_ordering
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
