# See https://github.com/dart-lang/mono_repo for details

# - format stage runs only on Linux and only using dev SDK
# - analyze stage runs only on Linux with different flags for 2.7.0 and dev SDKs
# - test stage runs for all oses and all sdks

stages:
  - format_analyze:
    - group:
      - format
      - analyze: --fatal-infos
      dart: [dev]
  - run_tests:
    - group: [test]
      dart: [dev]
      os: [linux, osx, windows]
