# See https://github.com/dart-lang/mono_repo for details
stages:
  - format_analyze:
    - group:
      - format
      - command: ./../tool/setup.sh
      - command: make protos
            # Fatal infos cannot be enabled until protoc_plugin source is
            # null safe.
      - analyze: --fatal-infos
      dart: [dev]
  - run_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - command: dart test
      dart: [2.12.0, dev]
