# See https://github.com/dart-lang/mono_repo for details
stages:
  - format_analyze:
    - group:
      - format: --output=none --set-exit-if-changed lib
      - command: ./../tool/setup.sh
      - command: make protos
      - analyze: --fatal-infos
      sdk: [dev]
  - run_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - test
      sdk: [pubspec, dev]
