# See https://github.com/dart-lang/mono_repo for details
stages:
  - format_analyze:
    - group:
      - format
      - command: ./../tool/setup.sh
      - command: make protos
      # Specify directores to exclude legacy_tests
      - analyze: --fatal-infos bin lib test
      sdk: [dev]
  - run_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - test
      sdk: [pubspec, dev]
  - run_legacy_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - test: legacy_tests/generated_message_test.dart
      sdk: [pubspec]
