# See https://github.com/dart-lang/mono_repo for details
stages:
  - format:
    - group:
      - command: ./../tool/setup.sh
      - dartfmt
      dart: [dev]
  - analyze:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
        # Fatal infos cannot be enabled until protoc_plugin source is
        # null safe.
      - dartanalyzer: --fatal-infos
      dart: [dev]
  - run_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - command: dart --no-sound-null-safety test
      dart: [2.12.0, dev]
