# See https://github.com/dart-lang/mono_repo for details
stages:
  - analyze:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - analyze: --fatal-infos
      sdk: [dev]
  - test:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - test
      sdk: [pubspec, dev]
