# See https://github.com/dart-lang/mono_repo for details

stages:
  - format_analyze:
    - group:
      - format
      - command: ./../tool/setup.sh
      - command: ./tool/compile_protos.sh
      - analyze: --fatal-infos
      sdk: dev
